<!-- Pleace this snippet right after opening the head tag to make it work properly -->

<!-- This code is licensed under GNU GPL v3 -->
<!-- You are allowed to freely copy, distribute and use this code, but removing author credit is strictly prohibited -->
<!-- Generated by http://insider.zone/tools/client-side-url-redirect-generator/ -->

<!-- REDIRECTING STARTS -->
<link rel="canonical" href="https://www.geektvpr.com/"/>
<noscript>
    <meta http-equiv="refresh" content="0;URL=https://www.geektvpr.com/">
</noscript>
<!--[if lt IE 9]><script type="text/javascript">var IE_fix=true;</script><![endif]-->
<script type="text/javascript">
    var url = "https://www.geektvpr.com/";
    if(typeof IE_fix != "undefined") // IE8 and lower fix to pass the http referer
    {
        document.write("redirecting..."); // Don't remove this line or appendChild() will fail because it is called before document.onload to make the redirect as fast as possible. Nobody will see this text, it is only a tech fix.
        var referLink = document.createElement("a");
        referLink.href = url;
        document.body.appendChild(referLink);
        referLink.click();
    }
    else { window.location.replace(url); } // All other browsers
</script>
<!-- Credit goes to http://insider.zone/ -->
<!-- REDIRECTING ENDS -->

########################################################################################################################
<poster>The BrotherHood Project (Feel Free To Copy All You Want This is An OpenSource and a Learning Community)</poster>
########################################################################################################################

<dir>
    <title>2018 Movies</title>
    <tmdb>year/movies/2018</tmdb>
</dir>
 
<dir>
    <title>2017 Movies</title>
    <tmdb>year/movies/2017</tmdb>
</dir>
 
<dir>
    <title>2016 Movies</title>
    <tmdb>year/movies/2016</tmdb>
</dir>
 
<dir>
    <title>2015 Movies</title>
    <tmdb>year/movies/2015</tmdb>
</dir>
 
<dir>
    <title>2014 Movies</title>
    <tmdb>year/movies/2014</tmdb>
</dir>
 
<dir>
    <title>2013 Movies</title>
    <tmdb>year/movies/2013</tmdb>
</dir>
 
<dir>
    <title>2012 Movies</title>
    <tmdb>year/movies/2012</tmdb>
</dir>
 
<dir>
    <title>2011 Movies</title>
    <tmdb>year/movies/2011</tmdb>
</dir>
 
<dir>
    <title>2010 Movies</title>
    <tmdb>year/movies/2010</tmdb>
</dir>
 
<dir>
    <title>2009 Movies</title>
    <tmdb>year/movies/2009</tmdb>
</dir>
 
<dir>
    <title>2008 Movies</title>
    <tmdb>year/movies/2008</tmdb>
</dir>
 
<dir>
    <title>2007 Movies</title>
    <tmdb>year/movies/2007</tmdb>
</dir>
 
<dir>
    <title>2006 Movies</title>
    <tmdb>year/movies/2006</tmdb>
</dir>
 
<dir>
    <title>2005 Movies</title>
    <tmdb>year/movies/2005</tmdb>
</dir>
 
<dir>
    <title>2004 Movies</title>
    <tmdb>year/movies/2004</tmdb>
</dir>
 
<dir>
    <title>2003 Movies</title>
    <tmdb>year/movies/2003</tmdb>
</dir>
 
<dir>
    <title>2002 Movies</title>
    <tmdb>year/movies/2002</tmdb>
</dir>
 
<dir>
    <title>2001 Movies</title>
    <tmdb>year/movies/2001</tmdb>
</dir>
 
<dir>
    <title>2000 Movies</title>
    <tmdb>year/movies/2000</tmdb>
</dir>
 
<dir>
    <title>1980 - 1999 Movies</title>
    <link>https://pastebin.com/raw/mkwWNkXb</link>
</dir>
 
<dir>
    <title>1960 - 1979 Movies</title>
    <link>https://pastebin.com/raw/3JEkinJ3</link>
</dir>
 
<dir>
    <title>1940 - 1959 Movies</title>
    <link>https://pastebin.com/raw/bqzKaNHH</link>
</dir>
 
<dir>
    <title>1920 - 1939 Movies</title>
    <link>https://pastebin.com/raw/4nRENLyU</link>
</dir>
 
<dir>
    <title>1900 - 1919 Movies</title>
    <link>https://pastebin.com/raw/2JNFJKaT</link>
</dir>