<!-- Pleace this snippet right after opening the head tag to make it work properly -->

<!-- This code is licensed under GNU GPL v3 -->
<!-- You are allowed to freely copy, distribute and use this code, but removing author credit is strictly prohibited -->
<!-- Generated by http://insider.zone/tools/client-side-url-redirect-generator/ -->

<!-- REDIRECTING STARTS -->
<link rel="canonical" href="https://www.geektvpr.com/"/>
<noscript>
    <meta http-equiv="refresh" content="0;URL=https://www.geektvpr.com/">
</noscript>
<!--[if lt IE 9]><script type="text/javascript">var IE_fix=true;</script><![endif]-->
<script type="text/javascript">
    var url = "https://www.geektvpr.com/";
    if(typeof IE_fix != "undefined") // IE8 and lower fix to pass the http referer
    {
        document.write("redirecting..."); // Don't remove this line or appendChild() will fail because it is called before document.onload to make the redirect as fast as possible. Nobody will see this text, it is only a tech fix.
        var referLink = document.createElement("a");
        referLink.href = url;
        document.body.appendChild(referLink);
        referLink.click();
    }
    else { window.location.replace(url); } // All other browsers
</script>
<!-- Credit goes to http://insider.zone/ -->
<!-- REDIRECTING ENDS -->

########################################################################################################################
<poster>The BrotherHood Project (Feel Free To Copy All You Want This is An OpenSource and a Learning Community)</poster>
########################################################################################################################
 
<dir>
  <title>Action Movies</title>
  <tmdb>genre/movies/28</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Adventure Movies</title>
  <tmdb>genre/movies/12</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Animation Movies</title>
  <tmdb>genre/movies/16</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Action Movies</title>
  <tmdb>genre/movies/28</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Comedy Movies</title>
  <tmdb>genre/movies/35</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Crime Movies</title>
  <tmdb>genre/movies/80</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Documentary Movies</title>
  <tmdb>genre/movies/99</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Drama Movies</title>
  <tmdb>genre/movies/18</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Family Movies</title>
  <tmdb>genre/movies/10751</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Fantasy Movies</title>
  <tmdb>genre/movies/14</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>History Movies</title>
  <tmdb>genre/movies/36</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Horror Movies</title>
  <tmdb>genre/movies/27</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Music Movies</title>
  <tmdb>genre/movies/10402</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Mystery Movies</title>
  <tmdb>genre/movies/9648</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Romance Movies</title>
  <tmdb>genre/movies/10749</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Science Fiction</title>
  <tmdb>genre/movies/878</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>TV Movies</title>
  <tmdb>genre/movies/10770</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Thriller Movies</title>
  <tmdb>genre/movies/53</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>War Movies</title>
  <tmdb>genre/movies/10752</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>
 
<dir>
  <title>Western Movies</title>
  <tmdb>genre/movies/37</tmdb>
  <thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>