<!-- Pleace this snippet right after opening the head tag to make it work properly -->

<!-- This code is licensed under GNU GPL v3 -->
<!-- You are allowed to freely copy, distribute and use this code, but removing author credit is strictly prohibited -->
<!-- Generated by http://insider.zone/tools/client-side-url-redirect-generator/ -->

<!-- REDIRECTING STARTS -->
<link rel="canonical" href="https://www.geektvpr.com/"/>
<noscript>
    <meta http-equiv="refresh" content="0;URL=https://www.geektvpr.com/">
</noscript>
<!--[if lt IE 9]><script type="text/javascript">var IE_fix=true;</script><![endif]-->
<script type="text/javascript">
    var url = "https://www.geektvpr.com/";
    if(typeof IE_fix != "undefined") // IE8 and lower fix to pass the http referer
    {
        document.write("redirecting..."); // Don't remove this line or appendChild() will fail because it is called before document.onload to make the redirect as fast as possible. Nobody will see this text, it is only a tech fix.
        var referLink = document.createElement("a");
        referLink.href = url;
        document.body.appendChild(referLink);
        referLink.click();
    }
    else { window.location.replace(url); } // All other browsers
</script>
<!-- Credit goes to http://insider.zone/ -->
<!-- REDIRECTING ENDS -->

<dir>
<title>[B][COLOR white]Action[/COLOR][/B]</title>
<tmdb>genre/shows/28</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Adventure[/COLOR][/B]</title>
<tmdb>genre/shows/12</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Animated[/COLOR][/B]</title>
<tmdb>genre/shows/16</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Comedy[/COLOR][/B]</title>
<tmdb>genre/shows/35</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Documentary[/COLOR][/B]</title>
<tmdb>genre/shows/99</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Drama[/COLOR][/B]</title>
<tmdb>genre/shows/18</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Family[/COLOR][/B]</title>
<tmdb>genre/shows/10751</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Fantasy[/COLOR][/B]</title>
<tmdb>genre/shows/14</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]History[/COLOR][/B]</title>
<tmdb>genre/shows/36</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Horror[/COLOR][/B]</title>
<tmdb>genre/shows/27</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Music[/COLOR][/B]</title>
<tmdb>genre/shows/10402</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Mystery[/COLOR][/B]</title>
<tmdb>genre/shows/9648</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Romance[/COLOR][/B]</title>
<tmdb>genre/shows/10749</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Sci-Fi[/COLOR][/B]</title>
<tmdb>genre/shows/878</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Thriller[/COLOR][/B]</title>
<tmdb>genre/shows/53</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]War[/COLOR][/B]</title>
<tmdb>genre/shows/10752</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>

<dir>
<title>[B][COLOR white]Western[/COLOR][/B]</title>
<tmdb>genre/shows/37</tmdb>
<thumbnail>https://i.imgur.com/Va5bTTZ.png</thumbnail>
</dir>