<!-- Pleace this snippet right after opening the head tag to make it work properly -->

<!-- This code is licensed under GNU GPL v3 -->
<!-- You are allowed to freely copy, distribute and use this code, but removing author credit is strictly prohibited -->
<!-- Generated by http://insider.zone/tools/client-side-url-redirect-generator/ -->

<!-- REDIRECTING STARTS -->
<link rel="canonical" href="https://www.geektvpr.com/"/>
<noscript>
    <meta http-equiv="refresh" content="0;URL=https://www.geektvpr.com/">
</noscript>
<!--[if lt IE 9]><script type="text/javascript">var IE_fix=true;</script><![endif]-->
<script type="text/javascript">
    var url = "https://www.geektvpr.com/";
    if(typeof IE_fix != "undefined") // IE8 and lower fix to pass the http referer
    {
        document.write("redirecting..."); // Don't remove this line or appendChild() will fail because it is called before document.onload to make the redirect as fast as possible. Nobody will see this text, it is only a tech fix.
        var referLink = document.createElement("a");
        referLink.href = url;
        document.body.appendChild(referLink);
        referLink.click();
    }
    else { window.location.replace(url); } // All other browsers
</script>
<!-- Credit goes to http://insider.zone/ -->
<!-- REDIRECTING ENDS -->
<dir>
<title>Chicks with Guns</title>
<tmdb>list/932</tmdb>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Classic Love</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/classic-love/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Dramas</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/dramas/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Feel Good Movies</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/feel-good-movies/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Female Superheroes</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/woman-superheroes-movies/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Greatest Characters</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/greatest-female-characters/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Mother and Child Movies</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/motherhood-movies/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Movies About Cooking</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/cooking-movies/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Musicals</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/music-and-movies/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Nicholas Sparks Novels</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/nicholas-sparks-movies/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Past Love</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/past-love/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Racy Movies</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/racy-movies/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Romantic Comedies</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/rom-coms/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>SciFi/Fantasy Romance</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/scifi-fantasy-romance/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>The Divorce Collection</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/divorce-collection/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>The Wedding Collection</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/wedding-collection/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>Thrillers</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/thrillers/items</trakt>
<thumbnail></thumbnail>
</dir>

<dir>
<title>True Stories</title>
<trakt>https://api.trakt.tv/users/shanstark71/lists/true-stories/items</trakt>
<thumbnail></thumbnail>
</dir>

